###

GET http://localhost:8080

###

GET http://localhost:8080/produtos

###

POST http://localhost:8080/produtos/
Content-Type: application/json

{
    "nome": "Celular",
    "descricao": "Branco",
    "preco": 90
}

###

PUT http://localhost:8080/produtos?id=2
Content-Type: application/json

{
    "nome": "Secador",
    "descricao": "Preto",
    "preco": 90
}

###
DELETE http://localhost:8080/produtos?id=3